apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80

