apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - nodePort: 32221
    port: 80
    targetPort: 80

