apiVersion: v1
kind: Service
metadata:
  name: nginx-service-np
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
  - nodePort: 32222
    port: 80
    targetPort: 80