#############################################
		# Please edit the object below. Lines beginning with a '#' will be ignored,
		# and an empty file will abort the edit. If an error occurs while saving this file will be
		# reopened with the relevant failures.
		#
		apiVersion: v1
		kind: Service
		metadata:
		  annotations:
			meta.helm.sh/release-name: prometheus
			meta.helm.sh/release-namespace: app
			service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
		  creationTimestamp: "2023-11-20T11:06:43Z"
		  finalizers:
		  - service.kubernetes.io/load-balancer-cleanup
		  labels:
			app.kubernetes.io/component: server
			app.kubernetes.io/instance: prometheus
			app.kubernetes.io/managed-by: Helm
			app.kubernetes.io/name: prometheus
			app.kubernetes.io/part-of: prometheus
			app.kubernetes.io/version: v2.47.2
			helm.sh/chart: prometheus-25.6.0
		  name: prometheus-server
		  namespace: app
		  resourceVersion: "697701"
		  uid: c6db43f1-9168-4c74-8f41-e56dd3348da2
		spec:
		  allocateLoadBalancerNodePorts: true
		  clusterIP: 10.100.229.44
		  clusterIPs:
		  - 10.100.229.44
		  externalTrafficPolicy: Cluster
		  internalTrafficPolicy: Cluster
		  ipFamilies:
		  - IPv4
		  ipFamilyPolicy: SingleStack
		  ports:
		  - name: http
			nodePort: 31611
			port: 80
			protocol: TCP
			targetPort: 9090
		  selector:
			app.kubernetes.io/component: server
			app.kubernetes.io/instance: prometheus
			app.kubernetes.io/name: prometheus
		  sessionAffinity: None
		  type: LoadBalancer
		status:
		  loadBalancer:
			ingress:
			- hostname: ac6db43f191684c748f41e56dd3348da-507624994.us-west-2.elb.amazonaws.com