apiVersion: v1
kind: Pod
metadata:                       
      name: hello-pod
      labels:
          app: webserver
spec:                               
    containers:
    -   name: hello-ctr
        image: jenkins/jenkins
        ports:
        -   containerPort: 80